test:
  variables:
    POSTGRES_VERSION: "12.5"
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "testing-password"
    POSTGRES_HOST_AUTH_METHOD: trust
    TEST_DATABASE_URL: postgres://postgres:testing-password@localhost/postgres
  services:
    - "postgres:${POSTGRES_VERSION}"
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/playpauseandstop/docker-python:4.0.0-py38
  needs: []
  script:
    - set -x
    - apt-get --allow-releaseinfo-change update
    - >-
      apt-get install --no-install-recommends -y
      build-essential
      libpq-dev
    - poetry install
    - DATABASE_URL=$TEST_DATABASE_URL poetry run yoyo apply -vvv -b
    - DATABASE_URL=${TEST_DATABASE_URL} poetry run pytest --cov=prediction tests --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  rules:
    - if: "$TEST_DISABLED"
      when: never
    - if: "$CI_COMMIT_TAG || $CI_COMMIT_BRANCH"
