---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kongconfig
data:
  kong.yml: |
    _format_version: "1.1"
    services:
    - url: "http://production-auto-deploy.kgsa-core-prediction-7489-production.svc:5000"
      routes:
      - paths:
        - "/"
      - hosts:
        - "kgsa.kochcloud.com"
        - "prediction.kgsa.kochcloud.com"
      plugins:
      - name: rate-limiting
        config:
          minute: 60
          policy: local
      - name: basic-auth
    consumers:
    - username: devin
      basicauth_credentials:
      - username: devin
        password: "Idle-Reflect-Disapprove-Harden-7"
    - username: badrul
      basicauth_credentials:
      - username: badrul
        password: "Congratulation-Cheer-Wrong-Salt-2"
    - username: maxim
      basicauth_credentials:
      - username: maxim
        password: "Lawyer-Stiffen-Apology-Pretty-0"
    - username: yeonjoo
      basicauth_credentials:
      - username: yeonjoo
        password: "Bill-Sadden-Handkerchief-Moreover-5"
    - username: siliconplains44
      basicauth_credentials:
      - username: siliconplains44
        password: "Guard-Sweeten-Place-Harm-1"
    - username: c3-dev
      basicauth_credentials:
      - username: c3-dev-fhr-lv
        password: "Universe-Week-Declare-Office-8"
