---
apiVersion: v1
kind: Service
metadata:
  name: kong
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:824505005505:certificate/5d5070a3-9d28-4c67-a36c-b321b4248cd6
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  ports:
    - name: kong-proxy-https
      port: 443
      targetPort: 8000
      protocol: TCP
  selector:
    app: kong
